2025-09-28 09:30:01.367 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration spotifyplus which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-09-28 09:30:01.370 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration adaptive_lighting which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-09-28 09:30:01.373 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-09-28 09:30:01.375 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration alexa_media which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-09-28 09:30:01.377 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration watchman which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2025-09-28 09:30:59.276 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open with args ('/usr/local/lib/python3.13/site-packages/pytz/zoneinfo/Africa/Abidjan', 'rb') inside the event loop by integration 'caldav' at homeassistant/components/caldav/coordinator.py, line 111: if not hasattr(event.instance, "vevent"): (offender: /usr/local/lib/python3.13/site-packages/pytz/__init__.py, line 108: return open(filename, 'rb')), please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+caldav%22
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 156, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once
    handle._run()
  File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 368, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 392, in _async_refresh
    self.data = await self._async_update_data()
  File "/usr/src/homeassistant/homeassistant/components/caldav/coordinator.py", line 111, in _async_update_data
    if not hasattr(event.instance, "vevent"):

2025-09-28 09:31:07.696 WARNING (MainThread) [homeassistant.components.light] Setup of light platform hue is taking over 10 seconds.
2025-09-28 09:31:07.697 WARNING (MainThread) [homeassistant.components.calendar] Setup of calendar platform caldav is taking over 10 seconds.
2025-09-28 09:31:07.697 WARNING (MainThread) [homeassistant.components.todo] Setup of todo platform caldav is taking over 10 seconds.
2025-09-28 09:31:55.816 WARNING (MainThread) [ring_doorbell.doorbot] Your Ring account does not have an active subscription.
2025-09-28 09:35:55.751 WARNING (MainThread) [ring_doorbell.doorbot] Your Ring account does not have an active subscription.
2025-09-28 09:38:56.533 WARNING (MainThread) [ring_doorbell.doorbot] Your Ring account does not have an active subscription.
2025-09-28 09:41:58.225 WARNING (MainThread) [ring_doorbell.doorbot] Your Ring account does not have an active subscription.
2025-09-28 09:44:59.794 WARNING (MainThread) [ring_doorbell.doorbot] Your Ring account does not have an active subscription.
2025-09-28 09:48:59.799 WARNING (MainThread) [ring_doorbell.doorbot] Your Ring account does not have an active subscription.
2025-09-28 09:52:59.748 WARNING (MainThread) [ring_doorbell.doorbot] Your Ring account does not have an active subscription.
2025-09-28 09:54:31.022 ERROR (MainThread) [pubnub] session.request exception: Connector is closed.
2025-09-28 09:54:39.558 WARNING (MainThread) [homeassistant.runner] Task could not be canceled and was still running after shutdown: <Task cancelling name='Task-900' coro=<FcmPushClient._listen() running at /usr/local/lib/python3.13/site-packages/firebase_messaging/fcmpushclient.py:728> wait_for=<Future pending cb=[Task.task_wakeup()]>>
